export const SET_CONTIAINER_CLASS = "SET_CONTIAINER_CLASS";
export const SET_LOGIN_WITH_MM = "SET_LOGIN_WITH_MM";
export const SET_USER_WALLET = "SET_USER_WALLET";
export const SET_LOADER = "SET_LOADER";
export const SET_SIGNUP_ERROR = "SET_SIGNUP_ERROR";
export const SET_SIGNUP_FORM = "SET_SIGNUP_FORM";
export const SET_IS_SIGNED_IN = "SET_IS_SIGNED_IN";
export const SET_SIGNIN_FORM = "SET_SIGNIN_FORM";
